hero/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls')),
    path('profile/', include('profiles.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('pay/<int:pk>', views.Pay.as_view(), name='pay'),
    path('saveorder/', views.SaveOrder.as_view(), name='saveorder'),
    path('list/', views.List.as_view(), name='list'),
    path('detail/<int:pk>', views.Detail.as_view(), name='detail'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ListProducts.as_view(), name='list'),
    path('<slug>', views.ProductDetail.as_view(), name='detail'),
    path('addtocart/', views.AddToCart.as_view(), name='addtocart'),
    path('removefromcart/', views.RemoveFromCart.as_view(), name='removefromcart'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('purchaseoverview/', views.PurchaseOverview.as_view(), name='purchaseoverview'),
    path('search/', views.Search.as_view(), name='search'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.Create.as_view(), name='create'),
    path('update/', views.Update.as_view(), name='update'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qnt_total = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=255)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    promo_price = models.FloatField(default=0)
    quantity = models.PositiveIntegerField()
    image = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.order}'

order/views.py
from typing import Any
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views import View
from django.contrib import messages

from product.models import Variation
from .models import Order, OrderItem

from utils import cart_tools


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('profiles:create')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(user=self.request.user)
        return qs


class Pay(DispatchLoginRequiredMixin, DetailView):
    template_name = 'order/pay.html'
    model = Order
    pk_url_kwarg = 'pk'
    context_object_name = 'order'


class SaveOrder(View):
    template_name= 'order/pay.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login para finalizar sua compra!'
            )
            return redirect('profiles:create')

        if not self.request.session.get('cart'):
            messages.error(
                self.request,
                'Seu carrinho está vazio!'
            )
            return redirect('product:list')

        cart = self.request.session.get('cart')
        cart_variation_ids = [v for v in cart]
        bd_variations = list(
            Variation.objects.select_related('product').filter(id__in=cart_variation_ids)
        )

        for variation in bd_variations:
            vid = str(variation.id)

            stock = variation.stock
            cart_qnt = cart[vid]['quantity']
            unt_price = cart[vid]['unit_price']
            unt_promo_price = cart[vid]['unit_promo_price']

            error_msg_stock = ''

            if stock < cart_qnt:
                cart[vid]['quantity'] = stock
                cart[vid]['quantitative_price'] = stock * unt_price
                cart[vid]['quantitative_promo_price'] = stock * unt_promo_price

                error_msg_stock = 'Estoque insuficiente para alguns produtos do seu carrinho. Reduzimos a quantidade desses produtos. Por favor, verifique quais produtos foram afetados a seguir.'

            if error_msg_stock:
                messages.error(
                    self.request,
                    error_msg_stock
                )

                self.request.session.save()
                return redirect('product:cart')

        qnt_cart_total = cart_tools.cart_total_qnt(cart)
        value_cart_total = cart_tools.cart_totals(cart)

        order = Order(
            user=self.request.user,
            total=value_cart_total,
            qnt_total=qnt_cart_total,
            status='C',
        )

        order.save()

        OrderItem.objects.bulk_create(
            [
                OrderItem(
                    order=order,
                    product=v['product_name'],
                    product_id=v['product_id'],
                    variation=v['variation_name'],
                    variation_id=v['variation_id'],
                    price=v['quantitative_price'],
                    promo_price=v['quantitative_promo_price'],
                    quantity=v['quantity'],
                    image=v['image'],
                ) for v in cart.values()
            ]
        )

        del self.request.session['cart']
        return redirect(
            reverse(
                'order:pay',
                kwargs={
                    'pk': order.pk
                }
            )
        )


class Detail(DispatchLoginRequiredMixin, DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'order/detail.html'
    pk_url_kwarg = 'pk'


class List(DispatchLoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'order/list.html'
    paginate_by = 10
    ordering = ['-id']

templates/partials/_cart.html
{% load static %}
{% load filters %}

<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>

        {% for product in cart.values %}
            <tr>
                <td class="d-none d-lg-block">
                    <img class="cart-img" src="{% get_media_prefix %}{{ product.image }}">
                </td>
                <td>
                    <a href="{% url "product:detail" product.slug %}">
                        {{ product.product_name }}
                    </a>

                    <a class="ml-3" href="{% url "product:removefromcart" %}?vid={{ product.variation_id }}">
                        <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                    </a>
                </td>
                <td>{{ product.variation_name }}</td>
                <td>
                    {{ product.quantity }} x
                    {% if product.unit_promo_price %}
                    {{ product.unit_promo_price|formatted_price }}
                    {% else %}
                    {{ product.unit_price|formatted_price }}
                    {% endif %}
                </td>

                {% if product.quantitative_promo_price %}
                <td>{{ product.quantitative_promo_price|formatted_price }}</td>
                {% else %}
                <td>{{ product.quantitative_price|formatted_price }}</td>
                {% endif %}
            </tr>
        {% endfor %}


    </table>
</div>

templates/partials/_footer.html
{% load static %}

<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Por Gustavo Fernandes</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static "assets/bootstrap/js/jquery-3.2.1.slim.min.js" %}"></script>
<script src="{% static "assets/bootstrap/js/popper.min.js" %}"></script>
<script src="{% static "assets/bootstrap/js/bootstrap.min.js" %}"></script>
<script defer src="{% static "assets/font-awesome/js/all.js" %}"></script>
<script src="{% static "assets/custom/js/scripts.js" %}"></script>

templates/partials/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap.css" %}">
<link rel="stylesheet" href="{% static "assets/custom/css/style.css" %}">

templates/partials/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/partials/_nav.html
{% load filters %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url "product:list" %}">Hero E-commerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Conta
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url "order:list" %}">Meus pedidos</a>
                    <a class="dropdown-item" href="{% url "profiles:create" %}">Atualizar dados</a>
                    <a class="dropdown-item" href="{% url "profiles:logout" %}">Sair</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "profiles:create" %}">Registrar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "profiles:create" %}">Entrar</a>
            </li>
            {% endif %}

            {% if request.session.cart %}
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="{% url "product:cart" %}">
                    <span class="nav-cart-text mr-1">
                        Carrinho
                    </span>
                    <span class="nav-cart-count mr-1">
                        <strong>{{ request.session.cart|cart_total_qnt }}x</strong>
                    </span>
                    <span class="nav-cart-icon mr-2">
                        <i class="fas fa-shopping-cart"></i>
                    </span>
                </a>
            </li>
            {% endif %}

        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url "product:search" %}">
            <input class="form-control mr-sm-2" type="search" name="term" value="{{ request.GET.term }}" placeholder="Buscar" aria-label="Buscar">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Buscar</button>
        </form>
    </div>
</nav>

templates/partials/_order.html
{% load static %}
{% load filters %}

<div class="row">
    <div class="col">
        <h3>{{ order }}</h3>

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{ order.id }}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{ order.total|formatted_price }}</div>

            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{ order.qnt_total }}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ order.get_status_display }}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>

                {% for line in order.orderitem_set.all %}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{% get_media_prefix %}{{ line.image }}">
                    </td>
                    <td>{{ line.product }}</td>
                    <td>{{ line.variation }}</td>
                    <td>{{ line.quantity }}</td>
                    <td>
                        {% if line.promo_price %}
                        {{ line.promo_price|formatted_price }}
                        {% else %}
                        {{ line.price|formatted_price }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

templates/partials/_pagination.html
{% if is_paginated %}

<div class="col mt-3 mb-3">
    <div class="row">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

{% endif %}