hero/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls')),
    path('profile/', include('profiles.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('pay/<int:pk>', views.Pay.as_view(), name='pay'),
    path('saveorder/', views.SaveOrder.as_view(), name='saveorder'),
    path('list/', views.List.as_view(), name='list'),
    path('detail/<int:pk>', views.Detail.as_view(), name='detail'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ListProducts.as_view(), name='list'),
    path('<slug>', views.ProductDetail.as_view(), name='detail'),
    path('addtocart/', views.AddToCart.as_view(), name='addtocart'),
    path('removefromcart/', views.RemoveFromCart.as_view(), name='removefromcart'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('purchaseoverview/', views.PurchaseOverview.as_view(), name='purchaseoverview'),
    path('search/', views.Search.as_view(), name='search'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.Create.as_view(), name='create'),
    path('update/', views.Update.as_view(), name='update'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

product/models.py
from django.db import models
from django.utils.text import slugify
from utils.resizer import resize_image
from utils import priceformatter


class Product(models.Model):
    name = models.CharField(max_length=255)
    short_description = models.TextField(max_length=255)
    long_description = models.TextField()
    image = models.ImageField(upload_to='product_images/%Y/%m/', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    marketing_price = models.FloatField(help_text='Obrigatório preencher na tabela abaixo mesmo se o produto não tiver variação.')
    promo_marketing_price = models.FloatField(default=0, help_text='Mantenha 0 se não existir preço promocional. Caso exista, preencher aqui e na tabela abaixo.')
    product_type = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variável'),
            ('S', 'Simples'),
        ),
        help_text=(
            'Variável: produto com diferentes variações (Ex.: P, M, G).<br>'
            'Simples: produto genérico que não possui variações específicas.'
        )
    )

    def get_formatted_price(self):
        return priceformatter.format_price(self.marketing_price)
    get_formatted_price.short_description = 'Price'

    def get_formatted_promo_price(self):
        return priceformatter.format_price(self.promo_marketing_price)
    get_formatted_promo_price.short_description = 'Promo Price'

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.name)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.image:
            resize_image(self.image, max_image_size)

    def __str__(self):
        return self.name


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True, null=True)
    price = models.FloatField()
    promo_price = models.FloatField(default=0)
    stock = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.name or self.product.name

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.contrib import messages
from django.db.models import Q

from . import models
from profiles.models import Profile


class ListProducts(ListView):
    model = models.Product
    template_name = 'product/list.html'
    context_object_name = 'products'
    paginate_by = 10
    ordering = ['-id']


class Search(ListProducts):
    def get_queryset(self, *args, **kwargs):
        term = self.request.GET.get('term') or self.request.session['term']
        qs = super().get_queryset(*args, **kwargs)

        if not term:
            return qs

        self.request.session['term'] = term

        qs = qs.filter(
            Q(name__icontains=term) |
            Q(short_description__icontains=term) |
            Q(long_description__icontains=term)
        )

        self.request.session.save()
        return qs


class ProductDetail(DetailView):
    model = models.Product
    template_name = 'product/detail.html'
    context_object_name = 'product'
    slug_url_kwarg = 'slug'


class AddToCart(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('product:list')
        )
        vid = self.request.GET.get('vid')

        if not vid:
            messages.error(
                self.request,
                'ERRO: O produto não existe!'
            )
            return redirect(http_referer)

        variation = get_object_or_404(models.Variation, id=vid)
        variation_stock = variation.stock
        product = variation.product

        product_id = product.id
        product_name = product.name
        variation_name = variation.name or ''
        unit_price = variation.price
        unit_promo_price = variation.promo_price
        quantity = 1
        slug = product.slug
        image = product.image

        if image:
            image = image.name
        else:
            image = ''

        if variation.stock < 1:
            messages.error(
                self.request,
                'ERRO: Estoque insuficiente!'
            )
            return redirect(http_referer)

        if not self.request.session.get('cart'):
            self.request.session['cart'] = {}
            self.request.session.save()

        cart = self.request.session['cart']

        if vid in cart:
            cart_quantity = cart[vid]['quantity']
            cart_quantity += 1

            if variation_stock < cart_quantity:
                messages.warning(
                    self.request,
                    f'Estoque insuficiente para {cart_quantity}x no produto "{product.name}". Há {variation_stock}x no seu carrinho.'
                )
                cart_quantity = variation_stock

            cart[vid]['quantity'] = cart_quantity
            cart[vid]['quantitative_price'] = unit_price * cart_quantity
            cart[vid]['quantitative_promo_price'] = unit_promo_price * cart_quantity
        else:
            cart[vid] = {
                'product_id': product_id,
                'product_name': product_name,
                'variation_name': variation_name,
                'variation_id': vid,
                'unit_price': unit_price,
                'unit_promo_price': unit_promo_price,
                'quantitative_price': unit_price,
                'quantitative_promo_price': unit_promo_price,
                'quantity': 1,
                'slug': slug,
                'image': image,
            }

        self.request.session.save()

        messages.success(
            self.request,
            f'Produto {product_name} {variation_name} adicionado ao seu carrinho {cart[vid]["quantity"]}x.'
        )

        return redirect(http_referer)


class RemoveFromCart(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('product:list')
        )
        vid = self.request.GET.get('vid')

        if not vid:
            return redirect(http_referer)
        
        if not self.request.session.get('cart'):
            return redirect(http_referer)
        
        if vid not in self.request.session['cart']:
            return redirect(http_referer)

        cart = self.request.session['cart'][vid]

        messages.success(
            self.request,
            f'Produto {cart["product_name"]} {cart["variation_name"]} removido do seu carrinho.'
        )

        del self.request.session['cart'][vid]
        self.request.session.save()
        return redirect(http_referer)


class Cart(View):
    def get(self, *args, **kwargs):
        context = {
            'cart': self.request.session.get('cart') 
        }

        return render(self.request, 'product/cart.html', context)


class PurchaseOverview(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('profiles:create')

        profile = Profile.objects.filter(user=self.request.user).exists()

        if not profile:
            messages.error(
                self.request,
                'Usuário sem perfil. Preencha os campos vazios.'
            )
            return redirect('profiles:create')

        if not self.request.session.get('cart'):
            messages.error(
                self.request,
                'Seu carrinho está vazio.'
            )
            return redirect('product:list')

        context = {
            'user': self.request.user,
            'cart': self.request.session['cart'],
        }

        return render(self.request, 'product/purchaseoverview.html', context)

product/templates/product/cart.html
{% extends "base.html" %}
{% load filters %}

{% block title %}Carrinho | {% endblock title %}

{% block content %}

{% if request.session.cart %}
    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho de compras</h3>
            <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

            {% include "partials/_cart.html" %}
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total</td>
                        <td>{{ cart|cart_totals|formatted_price }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">

            {% if request.user.is_authenticated %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url "product:purchaseoverview" %}">
                Comprar
            </a>
            {% else %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url "profiles:create" %}">
                Entre para comprar
            </a>
            {% endif %}
        </div>
    </div>
{% else %}
    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho vazio</h3>
            <p class="lead">Não há produtos no seu carrinho.</p>
    </div>
{% endif %}

{% endblock content %}

product/templates/product/detail.html
{% extends "base.html" %}
{% load filters %}

{% block title %}{{ product.name }} | {% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-lg">
            <div class="row no-gutters">
                <div class="col-lg-12">
                    {% if product.image %}
                        <img class="img-fluid" src="{{ product.image.url }}">
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg">
            <div class="mt-4 mt-lg-0">
                <h1 class="h2">{{ product.name }}</h1>
                <p class="lead">{{ product.short_description }}</p>
                <p class="lead">
                    {% if product.promo_marketing_price %}
                        <span id="variation-promo-price" class="lead product-price">
                            {{ product.promo_marketing_price|formatted_price }}
                        </span>
                        <span id="variation-price" class="lead product-old-price text-muted">
                            {{ product.marketing_price|formatted_price }}
                        </span>
                    {% else %}
                        <span id="variation-price" class="lead product-price">
                            {{ product.marketing_price|formatted_price }}
                        </span>
                    {% endif %}
                </p>

                <form action="{% url "product:addtocart" %}" id="form-add-to-cart">
                    <div class="form-group">
                        <select id="select-variation" name="vid" class="form-control form-control-lg">
                            {% for variation in product.variation_set.all %}

                            {% if variation.promo_price %}
                            <option data-price="{{ variation.price|formatted_price }}" data-promo-price="{{ variation.promo_price|formatted_price }}" value="{{ variation.id }}">
                                {% if variation.name %}
                                {{ variation.name }}
                                {% else %}
                                {{ variation }}
                                {% endif %}
                            </option>
                            {% else %}
                            <option data-price="{{ variation.price|formatted_price }}" value="{{ variation.id }}">
                                {% if variation.name %}
                                {{ variation.name }}
                                {% else %}
                                {{ variation }}
                                {% endif %}
                            </option>
                            {% endif %}

                            {% endfor %}
                        </select>
                    </div>

                    <div class="text-left">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            Adicionar ao carrinho
                        </button>
                    </div>

                </form>


            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="mt-5 mb-5">
                <h2 class="text-center">{{ product.name }}</h2>
                {{ product.long_description|linebreaks }}
            </div>
        </div>
    </div>
{% endblock content %}

product/templates/product/list.html
{% extends "base.html" %}
{% load filters %}

{% block title %}{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card-columns">

                {% for product in products %}
                    <div class="card">

                        {% if product.image %}
                            <a href="{% url "product:detail" product.slug %}">
                                <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
                            </a>
                        {% endif %}

                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.short_description }}</p>
                            <div class="container product-price-block text-center">

                                {% if product.promo_marketing_price %}
                                    <span class="product-price">
                                        {{ product.promo_marketing_price|formatted_price }}
                                    </span>
                                    <span class="product-old-price text-muted">
                                        {{ product.marketing_price|formatted_price }}
                                    </span>
                                {% else %}
                                    <span class="product-price">
                                        {{ product.marketing_price|formatted_price }}
                                    </span>
                                {% endif %}

                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="{% url "product:detail" product.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            {% include "partials/_pagination.html" %}
        </div>
    </div>
{% endblock content %}

product/templates/product/purchaseoverview.html
{% extends "base.html" %}
{% load filters %}

{% block title %}Resumo da compra | {% endblock title %}

{% block content %}

<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url "profiles:create" %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{ user.first_name }}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{ user.last_name }}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{ user.profile.age }}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{ user.profile.cpf }}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{ user.email }}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <p>Caso precise editar, <a href="{% url "profiles:create" %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{ user.profile.address }}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{ user.profile.address_number }}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{ user.profile.address_compliment }}</dd>
            <dt class="col-lg-2">Bairro:</dt>
            <dd class="col-lg-4">{{ user.profile.neighborhood }}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{ user.profile.city }}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{ user.profile.state }}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{ user.profile.cep }}</dd>
        </dl>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        <h3>Resumo do seu carrinho</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include "partials/_cart.html" %}
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        <p class="lead text-center"><span class="font-weight-bold">Total do carrinho:</span> {{ cart|cart_totals|formatted_price }}</p>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url "order:saveorder" %}">
            Realizar pedido
        </a>
    </div>
</div>

{% endblock content %}