hero/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls')),
    path('profile/', include('profiles.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('pay/<int:pk>', views.Pay.as_view(), name='pay'),
    path('saveorder/', views.SaveOrder.as_view(), name='saveorder'),
    path('list/', views.List.as_view(), name='list'),
    path('detail/<int:pk>', views.Detail.as_view(), name='detail'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qnt_total = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=255)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    promo_price = models.FloatField(default=0)
    quantity = models.PositiveIntegerField()
    image = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.order}'

order/views.py
from typing import Any
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views import View
from django.contrib import messages

from product.models import Variation
from .models import Order, OrderItem

from utils import cart_tools


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('profiles:create')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(user=self.request.user)
        return qs


class Pay(DispatchLoginRequiredMixin, DetailView):
    template_name = 'order/pay.html'
    model = Order
    pk_url_kwarg = 'pk'
    context_object_name = 'order'


class SaveOrder(View):
    template_name= 'order/pay.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login para finalizar sua compra!'
            )
            return redirect('profiles:create')

        if not self.request.session.get('cart'):
            messages.error(
                self.request,
                'Seu carrinho está vazio!'
            )
            return redirect('product:list')

        cart = self.request.session.get('cart')
        cart_variation_ids = [v for v in cart]
        bd_variations = list(
            Variation.objects.select_related('product').filter(id__in=cart_variation_ids)
        )

        for variation in bd_variations:
            vid = str(variation.id)

            stock = variation.stock
            cart_qnt = cart[vid]['quantity']
            unt_price = cart[vid]['unit_price']
            unt_promo_price = cart[vid]['unit_promo_price']

            error_msg_stock = ''

            if stock < cart_qnt:
                cart[vid]['quantity'] = stock
                cart[vid]['quantitative_price'] = stock * unt_price
                cart[vid]['quantitative_promo_price'] = stock * unt_promo_price

                error_msg_stock = 'Estoque insuficiente para alguns produtos do seu carrinho. Reduzimos a quantidade desses produtos. Por favor, verifique quais produtos foram afetados a seguir.'

            if error_msg_stock:
                messages.error(
                    self.request,
                    error_msg_stock
                )

                self.request.session.save()
                return redirect('product:cart')

        qnt_cart_total = cart_tools.cart_total_qnt(cart)
        value_cart_total = cart_tools.cart_totals(cart)

        order = Order(
            user=self.request.user,
            total=value_cart_total,
            qnt_total=qnt_cart_total,
            status='C',
        )

        order.save()

        OrderItem.objects.bulk_create(
            [
                OrderItem(
                    order=order,
                    product=v['product_name'],
                    product_id=v['product_id'],
                    variation=v['variation_name'],
                    variation_id=v['variation_id'],
                    price=v['quantitative_price'],
                    promo_price=v['quantitative_promo_price'],
                    quantity=v['quantity'],
                    image=v['image'],
                ) for v in cart.values()
            ]
        )

        del self.request.session['cart']
        return redirect(
            reverse(
                'order:pay',
                kwargs={
                    'pk': order.pk
                }
            )
        )


class Detail(DispatchLoginRequiredMixin, DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'order/detail.html'
    pk_url_kwarg = 'pk'


class List(DispatchLoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'order/list.html'
    paginate_by = 10
    ordering = ['-id']

order/templates/order/detail.html
{% extends "base.html" %}

{% load static %}
{% load filters %}

{% block title %}{{ pedido }} | {% endblock title %}

{% block content %}

<div class="d-flex justify-content-center mt-3 mb-3">
    <h1>Detalhes do seu pedido</h1>
</div>

{% include "partials/_order.html" %}

{% endblock content %}

order/templates/order/list.html
{% extends "base.html" %}
{% load filters %}

{% block title %}Pedidos de {{ user }} | {% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <h3 class="mb-4">Pedidos de {{ user }}</h3>
        <p>Abaixo todos os seus pedidos realizados no Hero.</p>

        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Pedido</th>
                    <th scope="col">Total</th>
                    <th scope="col">Qtd. Itens</th>
                    <th scope="col">Status</th>
                    <th scope="col">Mais detalhes</th>
                </tr>

                {% for order in orders %}
                <tr>
                    <th scope="row">{{ order }}</td>
                    <td>{{ order.total|formatted_price }}</td>
                    <td>{{ order.qnt_total }}</td>
                    <td>{{ order.get_status_display }}</td>
                    <td>
                        <a href="{% url "order:detail" order.id %}">
                            Ver <i class="fas fa-search-plus ml-2"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

{% include "partials/_pagination.html" %}

{% endblock content %}

order/templates/order/pay.html
{% extends "base.html" %}

{% load static %}
{% load filters %}

{% block title %}Pagamento | {% endblock title %}

{% block content %}
<div class="row">
    <div class="col">
        <h3>Escolha o método de pagamento</h3>
        <p>Para o desenvolvedor: adicione seu método de pagamento preferido.</p>
    </div>
</div>

{% include "partials/_order.html" %}

<div class="row mt-4">
    <div class="col">
        <a href="#" class="btn btn-primary btn-block btn-lg">Pagar</a>
    </div>
</div>

{% endblock content %}